---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack which calls other CloudFormation templates to create a pipeline with GitHub, CodePipeline, CodeBuild which deploys to a created ElasticBeanstalk environment, Additionally a private VPC, RDS and Elasticache cluster is setup'

Parameters:
  EBKeyPair:
    Description: SSH Keypair for instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: newacc-keypair
  GithubToken:
    Description: Github Oauth token for codepipeline to poll github repo
    Type: String

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc-template.yaml
      TimeoutInMinutes: '30'

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./securitygroup-template.yaml
      TimeoutInMinutes: '30'
      Parameters:
        VPC: !GetAtt VpcStack.Outputs.VPC

  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./rds-template.yaml
      TimeoutInMinutes: '30'
      Parameters:
        VPC: !GetAtt VpcStack.Outputs.VPC
        Subnets: !GetAtt VpcStack.Outputs.PrivateSubnets
        WebServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.WebServerSecurityGroup

  EbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./eb-template.yaml
      TimeoutInMinutes: '30'
      Parameters:
        VPC: !GetAtt VpcStack.Outputs.VPC
        Subnets: !GetAtt VpcStack.Outputs.PublicSubnets
        WebServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.WebServerSecurityGroup
        KeyPairName: !Ref EBKeyPair
        SPRINGDATASOURCEURL: !GetAtt RdsStack.Outputs.URL
        SPRINGDATASOURCEUSERNAME: !GetAtt RdsStack.Outputs.Username
        SPRINGDATASOURCEPASSWORD: !GetAtt RdsStack.Outputs.Password

  # ElastiCache stack, not implemented yet
#  ElastiCacheStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: ./elasticache-template.yaml
#      TimeoutInMinutes: '30'
#      Parameters:
#        VPC: !GetAtt VpcStack.Outputs.VPC
#        Subnets: !GetAtt VpcStack.Outputs.PrivateSubnets
#        WebServerSecurityGroup: !GetAtt EbStack.Outputs.Ec2SecurityGroup

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./pipeline-template.yaml
      TimeoutInMinutes: '30'
      Parameters:
        ElasticBeanstalkApplication: !GetAtt EbStack.Outputs.ElasticBeanstalkApplication
        ElasticBeanstalkEnvironment: !GetAtt EbStack.Outputs.ElasticBeanstalkEnvironment
        GitHubOAuth: !Ref GithubToken

  # DnsStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./dns-template.yaml
  #     TimeoutInMinutes: '30'

# Outputs: