---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: ./master-template.yaml'

Parameters:
  VPCIPRange:
    Description: The CIDR Block for the VPC
    Type: String
    ConstraintDescription: CIDR Block
    Default: 10.0.0.0/16
  VPCPublicSubnetCIDRBlocks:
    Description: 3 CIDR Blocks for the Public Subnets
    Type: CommaDelimitedList
    ConstraintDescription: Comma Seperated list of CIDR Blocks
    Default: 10.0.1.0/24,10.0.2.0/24,10.0.3.0/24
  VPCPrivateSubnetCIDRBlocks:
    Description: 2 CIDR blocks for the Private Subnets
    Type: CommaDelimitedList
    ConstraintDescription: Comma Seperated list of CIDR Blocks
    Default: 10.0.4.0/24,10.0.5.0/24,10.0.6.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCIPRange
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      VpcId: !Ref VPC
      CidrBlock: !Select [ 0, !Ref VPCPublicSubnetCIDRBlocks]
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs ]
      VpcId: !Ref VPC
      CidrBlock: !Select [ 1, !Ref VPCPublicSubnetCIDRBlocks]
  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 2, !GetAZs ]
      VpcId: !Ref VPC
      CidrBlock: !Select [ 2, !Ref VPCPublicSubnetCIDRBlocks]
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      VpcId: !Ref VPC
      CidrBlock: !Select [ 0, !Ref VPCPrivateSubnetCIDRBlocks]
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs ]
      VpcId: !Ref VPC
      CidrBlock: !Select [ 1, !Ref VPCPrivateSubnetCIDRBlocks]
  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 2, !GetAZs ]
      VpcId: !Ref VPC
      CidrBlock: !Select [ 2, !Ref VPCPrivateSubnetCIDRBlocks]
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  RouteToInternet:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet1RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  PublicSubnet2RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2
  PublicSubnet3RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet3

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC
        Parameters:
          - VPCIPRange
      - Label:
          default: Subnets
        Parameters:
          - VPCPublicSubnetCIDRBlocks
          - VPCPrivateSubnetCIDRBlocks
    ParameterLabels:
      VPCIPRange:
        default: "VPC CIDR"
      VPCPublicSubnetCIDRBlocks:
        default: "Public Subnet CIDRs"
      VPCPrivateSubnetCIDRBlocks:
        default: "Private Subnet CIDRs"

Outputs:
  VPC:
    Description: ID of the created VPC
    Value: !Ref VPC
  PublicSubnets:
    Description: Public subnets as a comma delemited list
    Value: !Join [',', [ !Ref PublicSubnet1, !Ref PublicSubnet2, !Ref PublicSubnet3]]
  PrivateSubnets:
    Description: Private subnets as a comma delemited list
    Value: !Join [',', [ !Ref PrivateSubnet1, !Ref PrivateSubnet2, !Ref PrivateSubnet3]]